name: API Tests with Newman

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: newman run AutomationExercise.com.postman_collection.json --environment automationexercise.com.postman_environment.json
